app/models/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from app import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(32), unique=True, nullable=False)
    user_email = db.Column(db.String(100), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'<User {self.username}>'

    # Метод, необходимый для Flask-Login
    def get_id(self):
        return str(self.id)

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_mail import Mail
from config import config


db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
mail = Mail()


def create_app(config_name='default'):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    mail.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    with app.app_context():
        db.create_all()

    return app


from . import models

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates/main')

from . import routes

app/main/routes.py
from flask import render_template
from . import main


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/about')
def about():
    return render_template('about.html')


@main.route('/contacts')
def contacts():
    return render_template('contacts.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">

</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
        <a href="{{ url_for('main.index') }}" class="navbar-brand">APP</a>
        <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a href="{{ url_for('main.index') }}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{{ url_for('main.about') }}" class="nav-link">About</a></li>
                <li class="nav-item"><a href="{{ url_for('main.contacts') }}" class="nav-link">Contacts</a></li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item"><a href="{{ url_for('auth.dashboard') }}" class="btn btn-outline-dark">{{ current_user.username }}</a></li>
                {% else %}
                    <li class="nav-item"><a href="{{ url_for('auth.login') }}" class="btn btn-outline-dark">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

<div class="container">
    <main>
        {% block content %}

        {% endblock %}
    </main>
</div>

<div class="container">
    <footer>
        <p>&copy; 2024 My Flask App</p>
    </footer>
</div>

</body>
</html>